### ISSUE TITLE
v4.4.4 don't works

### ISSUE THREAD

**Issue by ipmonline** [riklaunim/django-ckeditor#56]
Only show the default textarea in the admin section using RichTextField. It's works in v4.0.2 and Django 1.6 but not initialize ckeditor in the current version.

In javascript console I have the error:
Uncaught TypeError: undefined is not a function ckeditor-init.js:1 (anonymous function)

I don't use the CKEDITOR_JQUERY_URL because the jquery is loaded with django (/static/admin/js/jquery.js). If I use the value '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js' the textarea disappear. 

Any idea?

**Comment by riklaunim** [comment]
can you check if that external jquery is before ckeditor init?

**Comment by ipmonline** [comment]
Yes, it's before. And there isn't 404 errors.

```
<head>
    <title>...</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
    <!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/static/admin/css/ie.css" /><![endif]-->

    <script type="text/javascript">window.__admin_media_prefix__ = "/static/admin/";</script>
    <script type="text/javascript">window.__admin_utc_offset__ = "7200";</script>

    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script
    <style>.cke{visibility:hidden;}</style>
    <script type="text/javascript" src="/static/ckeditor/ckeditor-init.js"></script>
    <script type="text/javascript" src="/static/admin/js/collapse.js"></script>

    <meta name="robots" content="NONE,NOARCHIVE">
    <link rel="stylesheet" type="text/css" href="chrome-extension://cgndfbhngibokieehnjhbjkkhbfmhojo/css/validation.css">
</head>
```

![js_loading](https://cloud.githubusercontent.com/assets/2951116/4275805/c8b4a8b2-3cff-11e4-95dc-77ef643f1d77.png)

**Comment by riklaunim** [comment]
Odd case. Maybe that jQuery version doesn't like "jQuery(function(){" usage in https://github.com/riklaunim/django-ckeditor/blob/master/ckeditor/static/ckeditor/ckeditor-init.js

can you check which version is it?

**Comment by ipmonline** [comment]
jQuery v1.9.1

**Comment by riklaunim** [comment]
That shouldn't make any problems. Looks like I'll have to test it with few browsers and configs to see if it can be reproduced and fixed.

**Comment by ipmonline** [comment]
I test it in OSX 10.9.4 with Chrome v37.0.2062.120, Firefox v29.0.1, Firefox v32.0.1 and Safari v7.0.6.

**Comment by ipmonline** [comment]
I use Django 1.7 and Python 2.7.

Any solution?

**Comment by riklaunim** [comment]
I'll try look at the issue today/tomorrow.

**Comment by riklaunim** [comment]
new version of django-ckeditor released with some JS fixes. Should work now.

**Comment by ipmonline** [comment]
I have the same javascript error with v4.4.6: "Uncaught TypeError: undefined is not a function"
:(

**Comment by riklaunim** [comment]
without jQuery it would throw: TypeError: $ is not a function, so in your case it's something after jQuery ready block. Are you sure you are using the latest JS files (collectstatic etc) and if so can you see which line the error is referring to?

**Comment by ipmonline** [comment]
I serve the js files using Apache:

```
  Alias /static/ckeditor /lib/python2.7/ckeditor/static/ckeditor/
  <Location /static/ckeditor>
     SetHandler None
  </Location>
```

And the error is in the first line of ckeditor-init.js:

```
$(function() {
    initialiseCKEditor();
    initialiseCKEditorInInlinedForms();

    function initialiseCKEditorInInlinedForms() {
        $(".add-row a, .grp-add-handler").click(function () {
            initialiseCKEditor();
            return true;
        });
    }
});

function initialiseCKEditor() {
    $('textarea[data-type=ckeditortype]').each(function(){
        if($(this).data('processed') == "0" && $(this).attr('id').indexOf('__prefix__') == -1){
            $(this).data('processed',"1");
            CKEDITOR.replace($(this).attr('id'), $(this).data('config'));
        }
    });
}
```

**Comment by riklaunim** [comment]
does it work with the demo application locally ? It's hard to see a bug in it - either jQuery is missing somehow or something very odd.

**Comment by ipmonline** [comment]
It works now setting with external CKEDITOR_JQUERY_URL!

```
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
```

Thank you very much for your time! 

Regards.
